[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "9.0.1-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "7.2.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.50"

[[constraint]]
  branch = "master"
  name = "github.com/docker/docker"

[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "0.12.3"

[[constraint]]
  branch = "master"
  name = "github.com/skarademir/naturalsort"

[[constraint]]
  name = "github.com/vmware/govcloudair"
  version = "0.0.2"

[[constraint]]
  name = "github.com/vmware/govmomi"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/diskfs/go-diskfs"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "v2.2.2"
